INSERT INTO `travel_app_console`.`transport_company` (`transport_company_id`, `name`, `rating`, `type`) VALUES ('1', 'Transport Company A', '5', 'Bus');
INSERT INTO `travel_app_console`.`transport_company` (`transport_company_id`, `name`, `rating`, `type`) VALUES ('2', 'Transport Company B', '4', 'Bus');
INSERT INTO `travel_app_console`.`transport_company` (`transport_company_id`, `name`, `rating`, `type`) VALUES ('3', 'Transport Company C', '3', 'Bus');
INSERT INTO `travel_app_console`.`transport_company` (`transport_company_id`, `name`, `rating`, `type`) VALUES ('4', 'Transport Company D', '2', 'Bus');
INSERT INTO `travel_app_console`.`transport_company` (`transport_company_id`, `name`, `rating`, `type`) VALUES ('5', 'Transport Company E', '1', 'Bus');
INSERT INTO `travel_app_console`.`transport_company` (`transport_company_id`, `name`, `rating`, `type`) VALUES ('6', 'Transport Company F', '5', 'Bus');
INSERT INTO `travel_app_console`.`transport_company` (`transport_company_id`, `name`, `rating`, `type`) VALUES ('7', 'Transport Company G', '4', 'Bus');
INSERT INTO `travel_app_console`.`transport_company` (`transport_company_id`, `name`, `rating`, `type`) VALUES ('8', 'Transport Company H', '3', 'Bus');
INSERT INTO `travel_app_console`.`transport_company` (`transport_company_id`, `name`, `rating`, `type`) VALUES ('9', 'Transport Company I', '2', 'Bus');
INSERT INTO `travel_app_console`.`transport_company` (`transport_company_id`, `name`, `rating`, `type`) VALUES ('10', 'Transport Company J','1','Bus');